export const data = [
  { key: 'Carlos', value: 'This is the new one' },  // Updated value for Carlos
  { key: 'Lucas', value: 'Hash 12 - COLLIDES with Carlos' },
  { key: 'Daniel', value: 'Hashes to 15' },
  { key: 'Chris', value: 'Hashes to 7' },
  { key: 'Michael', value: 'Also hashes to 7' },
  { key: 'Pam', value: 'Hashes to 12' },
  { key: 'Erin', value: 'Hashes to 2' },
  { key: 'Jan', value: 'Hashes to 7' },
  { key: 'Kevin', value: 'Hashes to 1' },
  { key: 'Dwight', value: 'Hashes to 13' },
  { key: 'Andy', value: 'Hashes to 2' },
  { key: 'Karen', value: 'Hashes to 5' },
  { key: 'Kelly', value: 'Hashes to 15' },
  { key: 'Angela', value: 'Hashes to 0' },
  { key: 'Oscar', value: 'Hashes to 0' },
  { key: 'Creed', value: 'Hashes to 5' },
  { key: 'Toby', value: 'Hashes to 2' },
  { key: 'Ryan', value: 'Hashes to 4' },
  { key: 'Stanley', value: 'Hashes to 2' },
  { key: 'California', value: 'Hashes to 8' },
  { key: 'Phyllis', value: 'Hashes to 11' },
  { key: 'Meredith', value: 'Hashes to 4' },
  { key: 'David', value: 'Hashes to 4' },
  { key: 'Darryl', value: 'Hashes to 0' },
  { key: 'Pete', value: 'Hashes to 6' },
  { key: 'Packer', value: 'Hashes to 6' },
  { key: 'Mose', value: 'Hashes to 4' }
];