export const data = [
  { key: 'Carlos', value: 'This is the new one' },  // Updated value for Carlos
  { key: 'Lucas', value: 'Hash 12 - COLLIDES with Carlos' },
  { key: 'Daniel', value: 'King' },
  { key: 'Chris', value: 'King' },
  { key: 'Michael', value: 'Scott' },
  { key: 'Pam', value: 'Beasley' },
  { key: 'Erin', value: 'Hannon' },
  { key: 'Jan', value: 'Levinson' },
  { key: 'Kevin', value: 'Malone' },
  { key: 'Dwight', value: 'Schrute' },
  { key: 'Andy', value: 'Bernard' },
  { key: 'Karen', value: 'Fillipelli' },
  { key: 'Kelly', value: 'Kapoor' },
  { key: 'Angela', value: 'Martin' },
  { key: 'Oscar', value: 'Martinez' },
  { key: 'Creed', value: 'Bratton' },
  { key: 'Toby', value: 'Flenderson' },
  { key: 'Ryan', value: 'Howard' },
  { key: 'Stanley', value: 'Hudson' },
  { key: 'California', value: 'Robert' },
  { key: 'Phyllis', value: 'Lapin-Vance' },
  { key: 'Meredith', value: 'Palmer' },
  { key: 'David', value: 'Wallace' },
  { key: 'Darryl', value: 'Philbin' },
  { key: 'Pete', value: 'Miller' },
  { key: 'Packer', value: 'Todd' },
  { key: 'Mose', value: 'Schrute' }
];